const tracks=[
 {title:'Lose Yourself',year:'2002',note:'A pressure-cooker record built around preparation, nerves, opportunity and the need to act when the moment finally arrives.'},
 {title:'Stan',year:'2000',note:'A storytelling record that shows how a narrator, a voice and an increasingly uncomfortable perspective can carry an entire song.'},
 {title:'Till I Collapse',year:'2002',note:'Relentless delivery and a beat that feels like a training montage without needing to explain itself.'},
 {title:'Mockingbird',year:'2004',note:'A much quieter side of the writing: family, regret and trying to explain complicated adult problems to a child.'},
 {title:'The Way I Am',year:'2000',note:'Anger turned into structure. Dense writing, sharp rhythm and a refusal to sound comfortable.'},
 {title:'Rap God',year:'2013',note:'Technical flexing pushed into spectacle: speed, internal rhyme and the sheer amount of information packed into a performance.'}
];
const shows=[
 {title:'BREAKING BAD',meta:'2008–2013 · 5 seasons',img:'https://d.ibtimes.com/en/full/720293/walter-white.jpg',desc:'A chemistry teacher becomes a drug manufacturer, but the interesting part is not the premise. It is watching small choices compound until the person making them is almost unrecognizable.',tags:['transformation','consequences','power'],modal:'breaking'},
 {title:'BETTER CALL SAUL',meta:'2015–2022 · 6 seasons',img:'https://akns-images.eonline.com/eol_images/Entire_Site/202267/rs_1200x1200-220707122549-1200-AMC_bettter_call_saul_0000_BCS_607_GL_0719_0008-RT.jpg?crop=1200%3A1200%3Bcenter%2Ctop&fit=around%7C1200%3A1200&output-quality=90',desc:'A slower, stranger character study about Jimmy McGill, identity, compromise and the distance between the person you are and the person you decide to perform.',tags:['Jimmy McGill','identity','consequences'],modal:'saul'},
 {title:'THE SOPRANOS',meta:'1999–2007 · 6 seasons',img:'https://parade.com/.image/c_fill%2Cw_1200%2Ch_1200%2Cg_faces%3Acenter/MTkwNTc5NTY1OTIxMzc5NDUz/james-gandolfini-heart-attack-sopranos-ftr.jpg',desc:'Mob drama on the surface, family and psychology underneath. The series keeps mixing the ordinary with the threatening until neither feels separate.',tags:['family','power','dark comedy'],modal:'sopranos'},
 {title:'FRIENDS',meta:'1994–2004 · 10 seasons',img:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Friends_actors_montage.jpg',desc:'A comfort-show entry: six people, a familiar apartment, jokes that became cultural shorthand, and the Chandler / Joey dynamic that makes the whole thing lighter.',tags:['sitcom','friendship','comfort'],modal:'friends'},
 {title:'SHUTTER ISLAND',meta:'2010 · film',img:'https://upload.wikimedia.org/wikipedia/en/7/76/Shutterislandposter.jpg',desc:'Fog, an island, unreliable perception and a story designed to make the viewer question what they are seeing. It rewards a second watch.',tags:['mystery','psychology','atmosphere'],modal:'shutter'}
];
const tech=[['C / C++','low-level thinking, university work, data structures'],['Python','automation, experiments, bots and quick ideas'],['Web','HTML, CSS, JavaScript and making things people can actually use'],['AI','chatbots, prompts, APIs and figuring out what is genuinely useful'],['Discord Bots','commands, dashboards, memory, integrations and experiments'],['Git','version control and the painful lesson of saving working code'],['Windows','the operating system I actually spend most of my time inside'],['VS Code','the desk where most of the above turns into files']];
const modalData={
 eminem:{tag:'MUSIC / EMINEM',title:'The Eminem file',html:`<p>The appeal is the writing first. The jokes, anger, vulnerability and technical flexes all work because the delivery is precise.</p><div class="modal-grid"><div class="modal-tile"><h3>Why it works</h3><p>Internal rhyme, unusual phrasing, character voices and the ability to switch tone without warning.</p></div><div class="modal-tile"><h3>8 Mile</h3><p>The film gives the music a visual context: Detroit, rap battles, nerves and the need to prove yourself in public.</p></div><div class="modal-tile"><h3>Different eras</h3><p>Early Slim Shady is deliberately chaotic. The Marshall Mathers period is bigger and more exposed. Later work often leans harder into technical performance.</p></div><div class="modal-tile"><h3>The archive rule</h3><p>No giant lyric dumps. Listen to the records; this page is here to explain why they matter to the archive.</p></div></div>`},
 breaking:{tag:'SCREENS / BREAKING BAD',title:'The transformation',html:`<p>Walter White's story is structured around escalation. The show repeatedly gives him a choice, lets him justify it, and then shows the next choice becoming easier to make.</p><div class="modal-grid"><div class="modal-tile"><h3>Characters</h3><p>Walter, Jesse, Saul, Mike, Gus and Skyler all represent different responses to power, fear and control.</p></div><div class="modal-tile"><h3>Visual language</h3><p>Color, desert landscapes, tight framing and strange camera angles turn ordinary spaces into visual clues.</p></div><div class="modal-tile"><h3>The hook</h3><p>It is less about the chemistry than the consequences of repeatedly crossing a line.</p></div></div>`},
 saul:{tag:'SCREENS / BETTER CALL SAUL',title:'Jimmy → Saul',html:`<p>What makes Better Call Saul interesting is that the transformation is not a single switch. Jimmy keeps making small compromises while insisting he is still basically the same person.</p><div class="modal-grid"><div class="modal-tile"><h3>Jimmy McGill</h3><p>Charm, improvisation and a constant need to prove that he belongs.</p></div><div class="modal-tile"><h3>Saul Goodman</h3><p>A performance becomes a profession, then a shield, then an identity.</p></div><div class="modal-tile"><h3>The connection</h3><p>The series makes the Breaking Bad world richer by showing the personal cost behind characters we first met as supporting players.</p></div></div>`},
 sopranos:{tag:'SCREENS / THE SOPRANOS',title:'Ordinary / dangerous',html:`<p>The Sopranos works because mob violence and domestic boredom can occupy the same scene. Tony can be intimidating in one moment and arguing about dinner in the next.</p><div class="modal-grid"><div class="modal-tile"><h3>Family</h3><p>The word means two very different things throughout the series, and the tension between them drives a lot of the story.</p></div><div class="modal-tile"><h3>Dark comedy</h3><p>The show can make a scene funny without removing its consequences.</p></div></div>`},
 friends:{tag:'SCREENS / FRIENDS',title:'The comfort show',html:`<p>Friends belongs here for a different reason. It is lighter, familiar and easy to return to. The six-person dynamic is the engine, with Chandler and Joey providing one of the most memorable comic pairings.</p><div class="modal-grid"><div class="modal-tile"><h3>The apartment</h3><p>Familiar locations become part of the cast: apartments, Central Perk and the hallway between them.</p></div><div class="modal-tile"><h3>Why rewatch</h3><p>You know where the joke is going and still watch it land. That is a different kind of attachment.</p></div></div>`},
 shutter:{tag:'SCREENS / SHUTTER ISLAND',title:'The second watch',html:`<p>Shutter Island is built around atmosphere and uncertainty. The island feels like a physical version of the protagonist's increasingly unstable understanding of events.</p><div class="modal-grid"><div class="modal-tile"><h3>Atmosphere</h3><p>Storms, institutional corridors, fire and fog keep the environment hostile even before the story explains why.</p></div><div class="modal-tile"><h3>The trick</h3><p>The film rewards noticing details and then watching again after the ending changes the meaning of earlier scenes.</p></div></div>`},
 jijel:{tag:'TRAVEL / STARTING POINT',title:'Jijel',html:`<p>The website starts here because this is the reference point. Sea, hills, familiar roads and the feeling of knowing a place without needing a tourist guide to explain it.</p>`},
 alger:{tag:'TRAVEL / ALGERIA',title:'Alger',html:`<p>Alger is the bigger-city counterpoint: denser, louder and different in rhythm. It belongs on the route because the map does not stop at the hometown.</p>`},
 world:{tag:'TRAVEL / ELSEWHERE',title:'Elsewhere',html:`<p>The travel list stays intentionally open. Italy, Scotland, Albania and other places are possibilities, not a checklist carved in stone.</p>`},
 coding:{tag:'TECH / WORKBENCH',title:'What I actually do',html:`<p>Study computer science, write code, break code, fix code, build bots, experiment with web apps and keep learning tools that make ideas easier to turn into something real.</p><div class="modal-grid"><div class="modal-tile"><h3>University</h3><p>Programming, algorithms, data structures, mathematics and the parts of computer science that hurt before they click.</p></div><div class="modal-tile"><h3>Projects</h3><p>Discord bots, dashboards, web apps and experiments with AI.</p></div></div>`},
 gym:{tag:'THE REST / GYM',title:'Gym',html:`<p>A physical counterweight to sitting in front of a screen. Training is part of the routine, not a motivational poster.</p>`},
 gaming:{tag:'THE REST / GAMING',title:'Gaming',html:`<p>PC and PlayStation. Sometimes competition, sometimes exploration, sometimes just an excuse to disappear into a game for a while.</p>`},
 study:{tag:'THE REST / STUDY',title:'Study',html:`<p>Informatique mixed with mathematics: analysis, algebra, statistics, graphs, logic and the rest of university life. The goal is to get through the difficult parts and keep moving.</p>`},
 faith:{tag:'THE REST / FAITH',title:'Muslim first',html:`<p>Faith is part of the identity behind the rest of the website. It is shown here as a personal part of life, not as a lecture.</p>`}
};

const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function renderTracks(){ $('#track-list').innerHTML=tracks.map((t,i)=>`<button class="track" data-track="${i}"><span class="num">${String(i+1).padStart(2,'0')}</span><strong>${t.title}</strong><span>${t.year} ↗</span></button>`).join(''); }
function renderScreens(){ $('#screen-list').innerHTML=shows.map(s=>`<article class="screen-card" data-type="${s.meta.includes('film')?'film':'series'}"><button class="screen-image" aria-label="Open ${s.title}" data-image="${s.img}" data-title="${s.title}" style="background-image:url('${s.img}')"></button><div class="screen-info"><small>${s.meta}</small><h3>${s.title}</h3><p>${s.desc}</p><div class="screen-meta">${s.tags.map(x=>`<span>${x}</span>`).join('')}</div><button class="text-btn" data-modal="${s.modal}">OPEN THE FILE ↗</button></div></article>`).join(''); }
function renderTech(){ $('#tech-grid').innerHTML=tech.map((t,i)=>`<button class="tech-card" data-tech="${i}"><strong>${t[0]}</strong><small>${t[1]}</small></button>`).join(''); }
function openModal(key){const d=modalData[key];if(!d)return;$('#modal-content').innerHTML=`<span class="modal-tag">${d.tag}</span><h2>${d.title}</h2>${d.html}`;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';}
function closeModal(){ $('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true');document.body.style.overflow=''; }
function observeReveals(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});$$('.reveal').forEach(e=>io.observe(e));}
renderTracks();renderScreens();renderTech();observeReveals();

const liveMessages=['currently somewhere between code, music & sleep','probably opening VS Code again','another tab, another idea','Jijel / Algeria / wherever next','music on, browser full of tabs'];
let liveIndex=0;
setInterval(()=>{liveIndex=(liveIndex+1)%liveMessages.length;const el=$('#live-message');if(el)el.textContent=liveMessages[liveIndex]},5200);
function updateClock(){const d=new Date();const t=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});const el=$('#live-clock');if(el)el.textContent='JIJEL · '+t} updateClock(); setInterval(updateClock,30000);

$$('.filter').forEach(btn=>btn.addEventListener('click',()=>{ $$('.filter').forEach(x=>x.classList.remove('active')); btn.classList.add('active'); const type=btn.dataset.filter; $$('.screen-card').forEach(card=>card.hidden=type!=='all'&&card.dataset.type!==type); }));

document.addEventListener('click',e=>{
 const image=e.target.closest('[data-image]');if(image){openImage(image.dataset.image,image.dataset.title);return}
 const scroll=e.target.closest('[data-scroll]'); if(scroll){e.preventDefault();document.getElementById(scroll.dataset.scroll)?.scrollIntoView({behavior:'smooth'});return}
 const modal=e.target.closest('[data-modal]');if(modal){openModal(modal.dataset.modal);return}
 const track=e.target.closest('[data-track]');if(track){const t=tracks[+track.dataset.track];openModal('eminem');setTimeout(()=>{$('#modal-content').insertAdjacentHTML('beforeend',`<div class="modal-tile" style="margin-top:20px"><span class="modal-tag">SELECTED TRACK</span><h3>${t.title} / ${t.year}</h3><p>${t.note}</p></div>`);},20);return}
 const techBtn=e.target.closest('[data-tech]');if(techBtn){const t=tech[+techBtn.dataset.tech];openModal('coding');setTimeout(()=>{$('#modal-content').insertAdjacentHTML('beforeend',`<div class="modal-tile" style="margin-top:20px"><span class="modal-tag">TECH FILE</span><h3>${t[0]}</h3><p>${t[1]}</p></div>`);},20);}
 if(e.target.closest('[data-close]'))closeModal();
});
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});

const sections=$$('.page-section'), navLinks=$('.site-header nav')?.querySelectorAll('a');
const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){navLinks?.forEach(a=>a.classList.toggle('active',a.dataset.scroll===entry.target.id))}}),{rootMargin:'-45% 0px -45% 0px'});sections.forEach(s=>sectionObserver.observe(s));
const dot=$('.cursor-dot'),ring=$('.cursor-ring');window.addEventListener('mousemove',e=>{dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px';ring.style.left=e.clientX+'px';ring.style.top=e.clientY+'px'});
